### ISSUE TITLE
runValidators not working for required fields while put request to update document in database

### ISSUE THREAD

**Issue by kirtann** [kirtann/MERN-ECOMMERCE#1]
### runValidators not working while updating the document in database. How can I solve this issue.

```
exports.updateProfile = catchAsyncErrors(async (req, res, next) => {
  const newUserData = {
    name: req.body.name,
    email: req.body.email,
  };

  // I will add cloudinary later

  const user = await User.findOneAndUpdate(
    { _id: req.user.id },
    { $set: newUserData },
    {
      new: true,
      runValidators: true,
      useFindAndModify: false,
    }
  );

  res.status(200).json({
    success: true,
    user,
  });
});
```

**In this code sample i am updating the user details and have a user model which has required true for name and email but using runValidators it doesn't check the validation for required true field. I want to solve this issue. And how can I achieve it**

**Comment by DJp119** [comment]
I guess remove the validator , even i was using to validate the condition for the email , it was not working .

**Comment by PatelNeelMahesh** [comment]
exports.updateProfile = catchAsyncErrors(async (req, res, next) => {
  const { name, email } = req.body;

  // Pre-validation
  if (!name || !email) {
    return res.status(400).json({
      success: false,
      message: 'Name and email are required',
    });
  }

  const newUserData = { name, email };

  const user = await User.findOneAndUpdate(
    { _id: req.user.id },
    { $set: newUserData },
    {
      new: true,
      runValidators: true,
      useFindAndModify: false,
    }
  );

  res.status(200).json({
    success: true,
    user,
  });
});

Check by adding Pre-Validation,

**Comment by kirtann** [comment]
Thanks. Appretiate this approach of adding a pre validation, and amazed to know that validators doesn't work for required fields.
Also to think of a different solution to this after learning to add a pre validator is to add a validation check in client side while submitting the form. I guess this will also work fine. But I will like using this approach

**Comment by PatelNeelMahesh** [comment]
@kirtann  You should explore formik and yep in to user in react for forms with them validation becomes easy.
